controller_list:
  - name: fake_gripper_controller
    joints:
      - jt5_joint
  - name: fake_arm_group_controller
    joints:
      - jt1_joint
      - jt2_joint
      - jt3_joint
      - jt4_joint
initial:  # Define initial robot poses.
  - group: arm_group
    pose: home