# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: arm_group
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - jt1_joint
    - jt2_joint
    - jt3_joint
    - jt4_joint
    - jt5_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: gripper_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      jt5_joint
arm_group_controller:
  type: velocity_controllers/JointTrajectoryController
  joints:
    - jt1_joint
    - jt2_joint
    - jt3_joint
    - jt4_joint
  gains:
    jt1_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    jt2_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    jt3_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    jt4_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1